vendor_remove_files += \
	lib/libAdobeReader.so \
	lib/libHTC_DIS.so \
	lib/libcallMaster.so \
	lib/libhtcsunny2engine.so \
	lib/librabjni-for-camera.so \
	lib/libkwmp3.so \
	lib/libLaputaEngine.so \
	lib/libcootek_pte_oem.so \
	lib/libIMClientCore.so \
	lib/libhtccamera.so \
	lib/libalbum_util2e.so \
	lib/libhtcqxdm2sd.so \
	lib/libtcpfinaggr.so \
	lib/libaudio_spreadtrum.so \
	lib/libttscompat.so \
	lib/libSR_AudioIn.so \
	lib/libAudioTrimmer.so \
	lib/libOlaEngineNew.so \
	lib/libttspico.so \
	lib/libctest.so \
	lib/libpphwrprovider.so \
	lib/libhtc_socketio.so \
	lib/libsqlite_jni.so \
	lib/libLaputaLbProviderJni.so \
	lib/libjUPnPCP.so \
	lib/libBrowserShell_UC.so \
	lib/libnativedocviewer.so \
	lib/libLaputaLbJni.so \
	lib/libpphwr.so \
	lib/libwsp_jni.so \
	lib/libhtc_dm.so \
	lib/libpim2jni.so \
	lib/libusbnetjni.so \
	lib/libamrEncode.so \
	lib/libthread_db.so \
	lib/libCTZip.so \
	etc/laputa/map_data.zip \
	etc/AIC3254_REG.csv \
	etc/CodecDSPID_WB.txt \
	etc/soundimage/Sound_Phone_Original_SPK_BCLK.txt \
	etc/soundimage/Sound_Pop.txt \
	etc/soundimage/Sound_Original_Recording_BCLK.txt \
	etc/soundimage/Sound_Jazz.txt \
	etc/soundimage/Sound_SRS_V_HP.txt \
	etc/soundimage/Sound_Latin.txt \
	etc/soundimage/Sound_R_B.txt \
	etc/soundimage/Sound_Treble_Booster.txt \
	etc/soundimage/srsfx_trumedia_movie.cfg \
	etc/AIC3254_REG_DualMicXC.csv \
	etc/soundimage/srsfx_trumedia_voice.cfg \
	etc/soundimage/Sound_Rock.txt \
	etc/soundimage/Sound_Blues.txt \
	etc/soundimage/Sound_Phone_Original_SPK_WB.txt \
	etc/soundimage/Sound_Phone_Original_HP_BCLK.txt \
	etc/soundimage/Sound_Bass_Booster.txt \
	etc/soundimage/Sound_SRS_A_HP.txt \
	etc/soundimage/Sound_Phone_Original_REC_BCLK.txt \
	etc/AIC3254_REG_DualMic.csv \
	etc/sdk/sdkinfo.xml \
	etc/DxDrmConfig_Server.txt \
	etc/soundimage/Sound_Classical.txt \
	etc/soundimage/Sound_Piano.txt \
	etc/soundimage/Sound_Phone_Original_REC_NEL.txt \
	etc/soundimage/srsfx_trumedia_51.cfg \
	etc/soundimage/Sound_New_Age.txt \
	etc/soundimage/Sound_SRS_V_SPK.txt \
	etc/soundimage/Sound_Original_BCLK.txt \
	etc/soundimage/Sound_SRS_A_SPK.txt \
	etc/soundimage/Sound_Original_SPK_BCLK.txt \
	etc/soundimage/Sound_Vocal_Booster.txt \
	etc/soundimage/Sound_Country.txt \
	etc/soundimage/srsfx_trumedia_music.cfg \
	etc/soundimage/srs_bypass.cfg \

# configuration for remove_drawables
remove_drawables += \
	com.htc.resources/res/drawable-hdpi/icon_btn_downloading04_light.png \
	com.htc.resources/res/drawable-hdpi/icon_tab_notifications.png \
	com.htc.resources/res/drawable-hdpi/icon_category_community.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_delete_light.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_gps.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_view_dark.png \
	com.htc.resources/res/drawable-hdpi/common_timer_tumblers_light_8.png \
	com.htc.resources/res/drawable-hdpi/common_b_detail_btn_left_rest.9.png \
	com.htc.resources/res/drawable-hdpi/icon_category_gas.png \
	com.htc.resources/res/drawable-hdpi/icon_indicator_reply_s.png \
	com.htc.resources/res/drawable-hdpi/icon_tab_thread.png \
	com.htc.resources/res/drawable-hdpi/icon_grid_setting.png \
	com.htc.resources/res/drawable-hdpi/icon_tab_updates.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_wifi.png \
	com.htc.resources/res/drawable-hdpi/zzzz_icon_btn_alarm_mute_light.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_pause_light.png \
	com.htc.resources/res/drawable-hdpi/weather_gl_raindrop_streaks_gl.png \
	com.htc.resources/res/drawable-hdpi/automotive_common_b_radiobutton_rest.png \
	com.htc.resources/res/drawable-hdpi/icon_category_vip_group.png \
	com.htc.resources/res/drawable-hdpi/icon_indicator_updates_dark_s.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_auto_dark.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_play_light.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_unlink_dark.png \
	com.htc.resources/res/drawable-hdpi/common_three_center.9.png \
	com.htc.resources/res/drawable-hdpi/icon_indicator_eating.png \
	com.htc.resources/res/drawable-hdpi/icon_tab_bookmark.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_link_dark.png \
	com.htc.resources/res/drawable-hdpi/common_panel_small.9.png \
	com.htc.resources/res/drawable-hdpi/common_preset_frame_rest.9.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_search_web_light.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_calendar.png \
	com.htc.resources/res/drawable-hdpi/weather_gl_mirage_lightyellow.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_watch.png \
	com.htc.resources/res/drawable-hdpi/common_tag_label_empty_rest.9.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_htcspeak.png \
	com.htc.resources/res/drawable-hdpi/common_widget_inputfield_bar.9.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_more_dark.png \
	com.htc.resources/res/drawable-hdpi/icon_default_located.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_search_light.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_beats_red_dark.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_up_dark.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_stop_refresh_dark.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_email_light.png \
	com.htc.resources/res/drawable-hdpi/icon_tab_friends.png \
	com.htc.resources/res/drawable-hdpi/common_header_l.9.png \
	com.htc.resources/res/drawable-hdpi/common_cc_button_rest.9.png \
	com.htc.resources/res/drawable-hdpi/lockscreen_number_keyin_rest.9.png \
	com.htc.resources/res/drawable-hdpi/zzzz_icon_btn_bluetooth_headset_light.png \
	com.htc.resources/res/drawable-hdpi/common_three_left.9.png \
	com.htc.resources/res/drawable-hdpi/common_timer_tumblers_light_6.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_attachment_dark.png \
	com.htc.resources/res/drawable-hdpi/zzzz_icon_btn_bluetooth_light.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_2d_dark.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_folder_phone.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_calculator.png \
	com.htc.resources/res/drawable-hdpi/common_timer_tumblers_light_9.png \
	com.htc.resources/res/drawable-hdpi/weather_lightning_03.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_previous_song_dark.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_location_light.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_check_in_dark.png \
	com.htc.resources/res/drawable-hdpi/common_b_more_on.png \
	com.htc.resources/res/drawable-hdpi/icon_category_business.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_flickr.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_down_dark.png \
	com.htc.resources/res/drawable-hdpi/common_b_transport_small_pressed.png \
	com.htc.resources/res/drawable-hdpi/icon_category_vcs.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_video.png \
	com.htc.resources/res/drawable-hdpi/common_settings_3section_on_1.png \
	com.htc.resources/res/drawable-hdpi/icon_category_most_frequent.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_beats_light.png \
	com.htc.resources/res/drawable-hdpi/common_timer_tumblers_light_3.png \
	com.htc.resources/res/drawable-hdpi/icon_tab_attachment.png \
	com.htc.resources/res/drawable-hdpi/common_tab_bar.9.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_htc_enhancer_light.png \
	com.htc.resources/res/drawable-hdpi/common_button_small_outer.9.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_speaker_on_light.png \
	com.htc.resources/res/drawable-hdpi/zzzz_icon_btn_mobile_light.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_eq_dark.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_pause_dark.png \
	com.htc.resources/res/drawable-hdpi/common_detail_tab_right_rest.9.png \
	com.htc.resources/res/drawable-hdpi/weather_dust_air.png \
	com.htc.resources/res/drawable-hdpi/weather_panel.png \
	com.htc.resources/res/drawable-hdpi/icon_indicator_likes_dark_s.png \
	com.htc.resources/res/drawable-hdpi/zzzz_icon_btn_reminder_light.png \
	com.htc.resources/res/drawable-hdpi/common_settings_btn.png \
	com.htc.resources/res/drawable-hdpi/common_list_item_shadow.9.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_ringtone.png \
	com.htc.resources/res/drawable-hdpi/common_footer.9.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_data.png \
	com.htc.resources/res/drawable-hdpi/common_transport_middle_pressed.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_people_dark.png \
	com.htc.resources/res/drawable-hdpi/automotive_common_b_checkbox_on.png \
	com.htc.resources/res/drawable-hdpi/icon_indicator_crop_vertical.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_highlight_blue.png \
	com.htc.resources/res/drawable-hdpi/common_list.9.png \
	framework-htc-res/res/drawable-hdpi/stat_sys_wifi_signal_off.png \
	com.htc.resources/res/drawable-nodpi/widget_list_divider.9.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_locate_me_dark.png \
	com.htc.resources/res/drawable-hdpi/weather_fogtype.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_todo_task.png \
	com.htc.resources/res/drawable-hdpi/common_timer_tumblers_light_2.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_sort_dark.png \
	com.htc.resources/res/drawable-hdpi/common_timer_tumblers_light_5.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_htc.png \
	com.htc.resources/res/drawable-hdpi/icon_category_medical.png \
	com.htc.resources/res/drawable-hdpi/icon_indicator_shopping.png \
	com.htc.resources/res/drawable-hdpi/automotive_common_circle_rest.png \
	com.htc.resources/res/drawable-hdpi/icon_category_shopping.png \
	com.htc.resources/res/drawable-hdpi/common_b_transport_large_pressed.png \
	com.htc.resources/res/drawable-hdpi/common_tag_label_empty_pressed.9.png \
	com.htc.resources/res/drawable-hdpi/icon_category_leisure.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_show_me.png \
	com.htc.resources/res/drawable-hdpi/common_b_more_rest.png \
	com.htc.resources/res/drawable-hdpi/common_panel_white.9.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_airbus.png \
	com.htc.resources/res/drawable-hdpi/common_download_rest.png \
	com.htc.resources/res/drawable-hdpi/common_widget_outline_dark_lg.9.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_downloading07_light.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_fit_screen_dark.png \
	com.htc.resources/res/drawable-hdpi/icon_grid_charge_only.png \
	com.htc.resources/res/drawable-hdpi/common_three_right.9.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_sms_light.png \
	com.htc.resources/res/drawable-hdpi/common_settings_1x1.png \
	com.htc.resources/res/drawable-hdpi/common_panel_white_radius.9.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_skin.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_sync_all.png \
	com.htc.resources/res/drawable-hdpi/common_unlink_on.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_location_search.png \
	com.htc.resources/res/drawable-hdpi/toggle_on.png \
	com.htc.resources/res/drawable-hdpi/common_timer_tumblers_light_1.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_brightness_light.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_phone.png \
	com.htc.resources/res/drawable-hdpi/common_tag_label_empty_outer.9.png \
	com.htc.resources/res/drawable-hdpi/icon_default_brightness.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_auto_rotate.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_show_keypad_dark_l.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_highlight_clear.png \
	com.htc.resources/res/drawable-hdpi/icon_indicator_community.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_copy_dark.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_wallpaper.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_settings.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_downloading00_light.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_surround_light.png \
	com.htc.resources/res/drawable-hdpi/icon_indicator_business.png \
	com.htc.resources/res/drawable-hdpi/icon_indicator_normal.png \
	com.htc.resources/res/drawable-hdpi/automotive_common_b_checkbox_rest.png \
	com.htc.resources/res/drawable-hdpi/icon_category_family.png \
	com.htc.resources/res/drawable-hdpi/common_link_rest.png \
	com.htc.resources/res/drawable-hdpi/icon_category_lodging.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_play_dark.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_mobile_network.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_wifi_hotspot.png \
	com.htc.resources/res/drawable-hdpi/zzzz_icon_btn_bluetooth_mute_light.png \
	com.htc.resources/res/drawable-hdpi/icon_indicator_attraction.png \
	com.htc.resources/res/drawable-hdpi/weather_fall_sleet.png \
	com.htc.resources/res/drawable-hdpi/icon_tab_group_member_view.png \
	com.htc.resources/res/drawable-hdpi/common_header.9.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_sound_display.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_friendstream.png \
	com.htc.resources/res/drawable-hdpi/icon_tab_info.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_quick_lookup_dark.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_photo.png \
	com.htc.resources/res/drawable-hdpi/common_tab_round_bg.9.png \
	com.htc.resources/res/drawable-hdpi/common_settings_panel.png \
	com.htc.resources/res/drawable-hdpi/common_detail_tab_left_rest.9.png \
	com.htc.resources/res/drawable-hdpi/common_tab_round.9.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_people_light.png \
	com.htc.resources/res/drawable-hdpi/common_b_transport_large_outer.png \
	com.htc.resources/res/drawable-hdpi/automotive_common_b_radiobutton_on.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_updates_dark.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_cut_dark.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_speaker_on_dark.png \
	com.htc.resources/res/drawable-hdpi/lockscreen_number_press.9.png \
	com.htc.resources/res/drawable-hdpi/common_timer_tumblers_light_7.png \
	com.htc.resources/res/drawable-hdpi/icon_category_parking.png \
	com.htc.resources/res/drawable-hdpi/common_download_on.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_locked_dark.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_font_style.png \
	framework-htc-res/res/drawable-hdpi/ic_vd_retry.png \
	framework-htc-res/res/drawable-hdpi/ic_vd_mic_on.png \
	com.htc.resources/res/drawable-hdpi/weather_cold_thermometer.jpg \
	com.htc.resources/res/drawable-nodpi/popup_title_divider.9.png \
	com.htc.resources/res/drawable-hdpi/icon_default_warning.png \
	com.htc.resources/res/drawable-hdpi/icon_indicator_replies_light_s.png \
	com.htc.resources/res/drawable-hdpi/icon_indicator_forward_s.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_highlight_yellow.png \
	com.htc.resources/res/drawable-hdpi/icon_category_attraction.png \
	com.htc.resources/res/drawable-hdpi/common_widget_outline_dark.9.png \
	com.htc.resources/res/drawable-hdpi/toggle_off.png \
	com.htc.resources/res/drawable-hdpi/common_panel_small_dark.9.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_albums.png \
	com.htc.resources/res/drawable-hdpi/common_stroke.9.png \
	com.htc.resources/res/drawable-hdpi/icon_category_image.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_world_clock.png \
	com.htc.resources/res/drawable-hdpi/icon_tab_all_people.png \
	com.htc.resources/res/drawable-hdpi/weather_heatwaves.png \
	com.htc.resources/res/drawable-hdpi/icon_category_people.png \
	com.htc.resources/res/drawable-hdpi/common_btn.9.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_paste_dark.png \
	com.htc.resources/res/drawable-hdpi/icon_default_video_play_dark_s.png \
	com.htc.resources/res/drawable-hdpi/section_bottom_divider.9.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_set_my_home_light.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_settings_dark.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_next_song_dark.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_folder_starred.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_contact_card_dark.png \
	com.htc.resources/res/drawable-hdpi/common_transport_middle_outer.png \
	com.htc.resources/res/drawable-hdpi/icon_category_home.png \
	com.htc.resources/res/drawable-hdpi/common_b_detail_btn_right_rest.9.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_font_style_light.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_edit_light.png \
	com.htc.resources/res/drawable-hdpi/tips_thumbnail_pinch.png \
	com.htc.resources/res/drawable-hdpi/weather_cold_ice.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_store_dark.png \
	com.htc.resources/res/drawable-hdpi/common_panel_fullscreen_base.9.png \
	com.htc.resources/res/drawable-hdpi/icon_tab_table_of_content.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_stop_dark.png \
	com.htc.resources/res/drawable-hdpi/zzzz_icon_btn_speaker_off_light.png \
	com.htc.resources/res/drawable-hdpi/icon_category_transit.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_weather.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_scene.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_camcorder.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_downloading05_light.png \
	com.htc.resources/res/drawable-hdpi/common_timer_tumblers_light_4.png \
	com.htc.resources/res/drawable-hdpi/common_b_transport_small_rest.png \
	com.htc.resources/res/drawable-hdpi/common_settings_3section_on_2.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_tuning_down_dark_s.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_folders_light.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_beats_no_enhancer_light.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_facebook.png \
	com.htc.resources/res/drawable-hdpi/icon_tab_messages.png \
	com.htc.resources/res/drawable-hdpi/icon_indicator_sort_down.png \
	com.htc.resources/res/drawable-hdpi/icon_category_bank.png \
	com.htc.resources/res/drawable-hdpi/icon_category_favorites.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_srs51_light.png \
	com.htc.resources/res/drawable-hdpi/common_b_detail_btn_center_rest.9.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_search.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_brightness_dark.png \
	com.htc.resources/res/drawable-hdpi/weather_gl_lens_flare2.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_retry_light.png \
	com.htc.resources/res/drawable-hdpi/icon_category_all.png \
	com.htc.resources/res/drawable-hdpi/icon_default_video.png \
	com.htc.resources/res/drawable-hdpi/common_widget_icon_refresh.png \
	com.htc.resources/res/drawable-hdpi/icon_tab_links.png \
	com.htc.resources/res/drawable-hdpi/icon_indicator_replies_dark_s.png \
	com.htc.resources/res/drawable-hdpi/icon_tab_invitations.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_pdf_viewer.png \
	com.htc.resources/res/drawable-hdpi/icon_tab_starred.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_flash_on_dark.png \
	com.htc.resources/res/drawable-hdpi/common_detail_tab_center_rest.9.png \
	com.htc.resources/res/drawable-hdpi/common_more_on.png \
	com.htc.resources/res/drawable-hdpi/common_b_transport_small_outer.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_share_dark.png \
	com.htc.resources/res/drawable-hdpi/common_spinner.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_downloading_light.png \
	com.htc.resources/res/drawable-hdpi/icon_indicator_connected.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_usb2pc.png \
	com.htc.resources/res/drawable-hdpi/icon_grid_music.png \
	com.htc.resources/res/drawable-hdpi/icon_indicator_favorites.png \
	com.htc.resources/res/drawable-hdpi/icon_indicator_updates_light_s.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_downloading01_light.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_camera.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_voice_recorder.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_folder_sound_set.png \
	com.htc.resources/res/drawable-hdpi/common_progress_radio_off.png \
	com.htc.resources/res/drawable-hdpi/icon_indicator_private.png \
	com.htc.resources/res/drawable-hdpi/automotive_common_arrow_down.png \
	com.htc.resources/res/drawable-hdpi/common_link_on.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_downloading02_light.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_people.png \
	com.htc.resources/res/drawable-hdpi/icon_indicator_facebook_s.png \
	com.htc.resources/res/drawable-hdpi/icon_indicator_repeat.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_download_dark.png \
	com.htc.resources/res/drawable-hdpi/common_settings_3section_on_3.png \
	com.htc.resources/res/drawable-hdpi/common_btn_l.9.png \
	com.htc.resources/res/drawable-hdpi/weather_gl_mirage_white.png \
	com.htc.resources/res/drawable-hdpi/common_tab_two_left.9.png \
	com.htc.resources/res/drawable-hdpi/icon_indicator_location_s.png \
	com.htc.resources/res/drawable-hdpi/zzzz_icon_btn_speaker_pocket_light.png \
	com.htc.resources/res/drawable-hdpi/common_footer_update.9.png \
	com.htc.resources/res/drawable-hdpi/zzzz_icon_btn_reminder_mute_light.png \
	com.htc.resources/res/drawable-hdpi/common_b_subtract_rest.png \
	com.htc.resources/res/drawable-hdpi/common_preset_frame_pressed.9.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_web_light.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_mobile_video.png \
	com.htc.resources/res/drawable-hdpi/icon_indicator_presence_online.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_downloading03_light.png \
	com.htc.resources/res/drawable-hdpi/lockscreen_number_rest.9.png \
	framework-htc-res/res/drawable-hdpi/ic_vd_green_key.png \
	framework-htc-res/res/drawable-hdpi/app_voicedialer.png \
	com.htc.resources/res/drawable-hdpi/icon_indicator_plurk_s.png \
	com.htc.resources/res/drawable-hdpi/zzzz_icon_btn_speaker_on_light.png \
	com.htc.resources/res/drawable-hdpi/icon_indicator_leisure.png \
	com.htc.resources/res/drawable-hdpi/icon_category_group.png \
	com.htc.resources/res/drawable-hdpi/icon_indicator_crop_horizontal.png \
	com.htc.resources/res/drawable-hdpi/common_detail_tab_outer.9.png \
	com.htc.resources/res/drawable-hdpi/common_inputfield_caption.9.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_preview_dark.png \
	com.htc.resources/res/drawable-hdpi/icon_tab_check_in.png \
	com.htc.resources/res/drawable-hdpi/icon_indicator_calendar.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_video_trimming_dark.png \
	com.htc.resources/res/drawable-hdpi/common_notification_new_on.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_dock.png \
	com.htc.resources/res/drawable-hdpi/icon_tab_all_update.png \
	com.htc.resources/res/drawable-hdpi/lockscreen_number_delete.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_contact_card_light.png \
	com.htc.resources/res/drawable-hdpi/weather_clouds_08.png \
	com.htc.resources/res/drawable-hdpi/weather_gl_lens_flare.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_phone_light.png \
	com.htc.resources/res/drawable-hdpi/icon_category_dining.png \
	com.htc.resources/res/drawable-hdpi/common_timer_tumblers_light_pm.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_document.png \
	com.htc.resources/res/drawable-hdpi/weather_windy_type.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_srs_light.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_brightness.png \
	com.htc.resources/res/drawable-hdpi/icon_tab_status_updates.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_messages.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_highlight_red.png \
	com.htc.resources/res/drawable-hdpi/common_transport_middle_rest.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_personalize.png \
	com.htc.resources/res/drawable-hdpi/common_button_small_pressed.9.png \
	com.htc.resources/res/drawable-hdpi/common_label_color.9.png \
	com.htc.resources/res/drawable-hdpi/common_button_small_rest.9.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_powersaver.png \
	com.htc.resources/res/drawable-hdpi/common_rearrange_pressed.png \
	com.htc.resources/res/drawable-hdpi/icon_indicator_info_s.png \
	com.htc.resources/res/drawable-hdpi/common_list_div_top.9.png \
	com.htc.resources/res/drawable-hdpi/zzzz_icon_btn_settings_light.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_phone_dark.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_show_map_light.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_navigator_light.png \
	com.htc.resources/res/drawable-hdpi/icon_tab_photos_and_videos.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_library_dark.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_folder_all_people.png \
	com.htc.resources/res/drawable-hdpi/icon_default_video_play.png \
	com.htc.resources/res/drawable-hdpi/icon_tab_contact_card.png \
	com.htc.resources/res/drawable-hdpi/zzzz_icon_btn_vibrate_light.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_music.png \
	com.htc.resources/res/drawable-hdpi/icon_tab_conversations.png \
	com.htc.resources/res/drawable-hdpi/icon_category_trip.png \
	com.htc.resources/res/drawable-hdpi/lockscreen_number_outer.9.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_lockscreen.png \
	com.htc.resources/res/drawable-hdpi/common_settings_panel_on.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_media_share.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_downloading06_light.png \
	com.htc.resources/res/drawable-hdpi/common_timer_tumblers_light_0.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_full_screen_dark.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_highlight_green.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_beats_dark.png \
	com.htc.resources/res/drawable-hdpi/icon_indicator_attachment.png \
	com.htc.resources/res/drawable-hdpi/common_progress_radio_on.png \
	com.htc.resources/res/drawable-hdpi/icon_indicator_presence_away.png \
	com.htc.resources/res/drawable-hdpi/common_menu_panel_4round.9.png \
	com.htc.resources/res/drawable-hdpi/common_timer_tumblers_light_am.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_footprint.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_highlight.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_camera_dark.png \
	com.htc.resources/res/drawable-hdpi/common_more_rest.png \
	com.htc.resources/res/drawable-hdpi/automotive_icon_btn_previous_dark.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_3d_dark.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_folder.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_output_dark.png \
	com.htc.resources/res/drawable-hdpi/weather_windy_02.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_my_location_dark.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_display.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_surround_dark.png \
	com.htc.resources/res/drawable-hdpi/common_tab_round_rest.9.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_locations.png \
	com.htc.resources/res/drawable-hdpi/icon_category_vcf.png \
	com.htc.resources/res/drawable-hdpi/common_tab_two_right.9.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_usage_monitor.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_updates_light.png \
	com.htc.resources/res/drawable-hdpi/common_b_transport_large_rest.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_info_light.png \
	com.htc.resources/res/drawable-hdpi/icon_indicator_likes_light_s.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_switch_camera_light.png \
	com.htc.resources/res/drawable-hdpi/icon_category_friends.png \
	com.htc.resources/res/drawable-hdpi/common_gridview_delete.png \
	com.htc.resources/res/drawable-hdpi/icon_indicator_eassync_error_l.png \
	com.htc.resources/res/drawable-hdpi/common_unlink_rest.png \
	com.htc.resources/res/drawable-hdpi/common_b_subtract_on.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_notes.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_audio.png \
	com.htc.resources/res/drawable-hdpi/common_photo_bg.9.png \
	com.htc.resources/res/drawable-hdpi/common_b_cc_button_rest.9.png \
	com.htc.resources/res/drawable-hdpi/icon_default_video_play_light_s.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_share_light.png \
	com.htc.resources/res/drawable-hdpi/icon_launcher_programs.png \
	com.htc.resources/res/drawable-hdpi/common_panel_dark.9.png \
	com.htc.resources/res/drawable-hdpi/icon_indicator_sort_up.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_srs_dark.png \
	com.htc.resources/res/drawable-hdpi/icon_btn_srs51_dark.png \
	framework-htc-res/res/drawable-hdpi/ic_vd_mic_off.png \

